###################### Configuration File (BadBlock-MiniGame API) ######################
#MongoDatabase connection module
mongodb:
  #Service name
  name: "mongodb"
  #Database hostname
  hostname: ""
  #Database port
  port: 25565
  #Username (db)
  username: ""
  #Password (db)
  password: ""
  #Database name
  database: ""
  #Collection name
  pdatamanagercol: ""
#Chat module
chat:
  #Set to true to enable chat, to false to disable
  enabled: true
  #Message when players trying to chat when disabled.
  messageondisabled: '&cLe chat a été désactivé par un membre du Staff'
  #Lines to clear on chat clear
  lines: 500
  #Message to send when the chat got cleared
  messageonclear: '&9Le chat a été supprimé par un membre du Staff !'
  #Message on disabling chat
  msgdisable: '&9Vous venez de désactiver le chat !'
  #Message on enabling chat
  msgenable: "&9Vous venez d'activer le chat !"
commannd:
  nopermission: "&cVous n'avez pas la permission !"
rank:
  noexist: "&cCe grade n'existe pas !"
  setperm: "&cLa permission a bien été ajouté !"
  delperm: "&cLa permissions a bien été supprimé !"
  playernoexist: "&cCe joueur n'existe pas, création de celui ci !"
  setpower: "&cLe power a bien été mis à jour."
  settag: "&cLe tag a bien été mis à jour."
  setprefix: "&cLe prefix a bien été mis à jour."
  setsuffix: "&cLe suffix a bien été mis à jour."
  alreadyexist: "&cErreur, le rank existe déjà !"
  create: "&cLe rank a été crée avec succées !"