messages:
  incorrect-arguments: "&cArguments incorrectes !"
  create-world: "&aLe monde vide &6%world% &fa bien été créé !"
  alreadyexist-world: "&aLe monde %world% existe déjà !"
  prefix-warp: "&f[&6Warps&f] &f"
  create-warp: "%prefix% Le warp &6%warp% &fa bien été crée !"
  sign-created-warp: "%prefix% Le panneau pour le warp &6%warp% &fa été crée !"
  sign-selection-cancelled-warp: "%prefix% &cLa selection de panneau a été annulé !"
  sign-selection: "%prefix% Sélectionnez un panneau à l'aide d'un clique droit ! Refaites la commande pour annuler la sélection"
  sign-deleted-warp: "%prefix% Le panneau du warp &6%warp% &fa été supprimé !"
  remove-warp: "%prefix% Le warp %warp% a bien été supprimé !"
  enable-warp: "%prefix% Le warp &6%warp% &fa été &aactivé &f!"
  already-enabled-warp: "%prefix% Le warp &6%warp% &fest déjà activé &f!"
  already-disabled-warp: "%prefix% Le warp &6%warp% &fest déjà désactivé &f!"
  disable-warp: "%prefix% Le warp &6%warp% &fa été &cdésactivé &f!"
  is-disabled-warp: "%prefix% Le warp &6%warp% est &cdésactivé &f! Vous ne pouvez vous y téléporter !"
  doesnt-exist-warp: "%prefix% Ce warp n'existe pas ! -> &6/warp list"
  alreadyexist-warp: "%prefix% Le warp %warp% existe déjà !"
  teleport-warp: "%prefix% Téléportation au warp &6%warp% &fréussi !"
  list-warp:
    top-message:
      - "%prefix% Liste des warps"
      - " "
    none-warp: "%prefix% &cAucun warp existant !"
    enabled-warps:
      - "Warps &aactivé(s)&f:"
      - "&r&l%warps%"
    disabled-warps:
      - "Warps &cdésactivé(s):&f:"
      - "&7%warps%"
  help-warp:
    - "&fListe des commandes de warp: "
    - " &7> &6/warp create <name> &f- &7&oCréer un warp"
    - " &7> &6/warp remove <warp> &f- &7&oSupprimer un warp"
    - " &7> &6/warp <disable/enable> <warp> &f- &7&oActiver/Désactiver un warp"
    - " &7> &6/warp tp <warp> &f- &7&oSe téléporter à un warp"
    - " &7> &6/warp list &f- &7&oAfficher la liste des warps"
    - " &7> &6/warp addsigns <warp> &f- &7&oDésigner un panneau pour un warp"
signs:
  - "&fWarp: &6%warp%"
  - "Etat: %state%"
  - "&aCliquez pour vous"
  - "&atéléporter au warp"
signs-state:
  enabled: "&aActivé"
  disabled: "&cDésactivé"