###################### Configuration File (BadBlock-MiniGame API) ######################
#MongoDatabase connection module
mongodb:
  #Service name
  name: 'mongodb'
  #Database hostname
  hostname: ''
  #Database port
  port: 25565
  #Username (db)
  username: ''
  #Password (db)
  password: ''
  #Database name
  database: ''
  #Collection player name
  datamanagercol: ''
  #Collection rank name
  rankmanagercol: ''
#Chat module
chat:
  #Message when players trying to chat when disabled.
  messageondisabled: '&cLe chat a été désactivé par un membre du Staff'
  #Lines to clear on chat clear
  lines: 500
  #Message to send when the chat got cleared
  messageonclear: '&9Le chat a été supprimé par un membre du Staff !'
  #Message on disabling chat
  msgdisable: '&9Vous venez de désactiver le chat !'
  #Message on enabling chat
  msgenable: '&9Vous venez d'activer le chat !'
#Command Module (Permissions)
commannd:
  #Message to send when the player doesn't have enough perms.
  nopermission: '&cVous n'avez pas la permission !'
#Rank Messages
rank:
  #Message to send when the rank doesn't exist into database
  noexist: '&cCe grade n existe pas !'
  #Message to send when a permission got added
  setperm: '&cLa permission a bien été ajouté !'
  #Message to send when a permission got cleared
  delperm: '&cLa permissions a bien été supprimé !'
  #Message to send when the player doesn't exist into the database
  playernoexist: '&cCe joueur n existe pas, création de celui ci !'
  #Message to send when the power of the rank got updated.
  setpower: '&cLe power a bien été mis à jour.'
  #Message to send when the tag got updated
  settag: '&cLe tag a bien été mis à jour.'
  #Message to send when the prefix got updated
  setprefix: '&cLe prefix a bien été mis à jour.'
  #Message to send when the sufix got updated
  setsuffix: '&cLe suffix a bien été mis à jour.'
  #Message to send when the rank already exist into database
  alreadyexist: '&cErreur, le rank existe déjà !'
  #Message to send when the rank got created
  create: '&cLe rank a été crée avec succées !'