name: BadBlockWarps
version: @version@
main: fr.customentity.badblockwarps.BadBlockWarps
authors: [Badblock]
description: Simple warp plugin
commands:
  warp:
    aliases: [warps]
    description: warp command
  createemptyworld:
    aliases: [cew]
