<?php

return [
    'punishTypes' => [
        'unban' => 'Débannissement',
        'unbanip' => 'Débannissement IP',
        'unmute' => 'Débaîllonnement',
        'mute' => 'Baîllonnement',
        'muteip' => 'Baîllonnement IP',
        'ban' => 'Bannissement',
        'banip' => 'Bannissement IP',
        'tempban' => 'Bannissement temporaire',
        'btempban' => 'Bannisesment temporaire Pseudo/IP',
        'warn' => 'Avertissement',
        'kick' => 'Éjecté',
        'tempbanip' => 'Bannissement temporaire IP',
        'report' => 'Signalement automatique'
    ],

    'colorChat' => [
        "&b" => "Bleu clair",
        "&d" => "Rose",
        "&e" => "Jaune",
        "&f" => "Blanc",
        "&1" => "Bleu foncé",
        "&2" => "Vert foncé",
        "&3" => "Bleu/Aqua",
        "&5" => "Violet",
        "&7" => "Gris",
        "&8" => "Gris foncé",
        "&9" => "Bleu",
        "&f" => "Blanc",
        "&a&n" => "Vert clair souligné",
        "&b&n" => "Bleu clair souligné",
        "&c&n" => "Rouge clair souligné",
        "&d&n" => "Rose souligné",
        "&e&n" => "Jaune souligné",
        "&f&n" => "Blanc souligné",
        "&1&n" => "Bleu foncé souligné",
        "&2&n" => "Vert foncé souligné",
        "&3&n" => "Bleu/Aqua souligné",
        "&4&n" => "Rouge foncé souligné",
        "&5&n" => "Violet souligné",
        "&6&n" => "Orange/Gold souligné",
        "&7&n" => "Gris souligné",
        "&8&n" => "Gris foncé souligné",
        "&9&n" => "Bleu souligné",
        "&f&n" => "Blanc souligné",
        "&a&l" => "Vert clair gras",
        "&b&l" => "Bleu clair gras",
        "&c&l" => "Rouge clair gras",
        "&d&l" => "Rose gras",
        "&e&l" => "Jaune gras",
        "&f&l" => "Blanc gras",
        "&1&l" => "Bleu foncé gras",
        "&2&l" => "Vert foncé gras",
        "&3&l" => "Bleu/Aqua gras",
        "&4&l" => "Rouge foncé gras",
        "&5&l" => "Violet gras",
        "&6&l" => "Orange/Gold gras",
        "&7&l" => "Gris gras",
        "&8&l" => "Gris foncé gras",
        "&9&l" => "Bleu gras",
        "&f&l" => "Blanc gras",
        "&a&o" => "Vert clair italique",
        "&b&o" => "Bleu clair italique",
        "&c&o" => "Rouge clair italique",
        "&d&o" => "Rose italique",
        "&e&o" => "Jaune italique",
        "&f&o" => "Blanc italique",
        "&1&o" => "Bleu foncé italique",
        "&2&o" => "Vert foncé italique",
        "&3&o" => "Bleu/Aqua italique",
        "&4&o" => "Rouge foncé italique",
        "&5&o" => "Violet italique",
        "&6&o" => "Orange/Gold italique",
        "&7&o" => "Gris italique",
        "&8&o" => "Gris foncé italique",
        "&9&o" => "Bleu italique",
        "&f&o" => "Blanc italique"
    ]
];

